config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    resources :comments
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root: "post#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy

  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :content, length: { minimum: 5 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments

  def username
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.update(comments_params)

    redirect_to post_path(@post)
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comments_params)

    #  if @comment.save
    #     redirect_to post_path(@post)
    #  else
    #     render 'posts/show'
    #  end
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post) }
        format.js # renders create.js.erb
      else
        format.html { redirect_to post_path(@post), notice: 'Relply did not save. Please try again.' }
        format.js
      end
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.js
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:content).merge(user: current_user)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :is_user?, except: %i[index show new create]
  before_action :set_post, only: %i[edit show update destroy]

  def index
    @posts = Post.all.order(id: :desc)
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:success] = 'El artículo se creo'
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:success] = 'El artículo fue editado correctamente'
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'El post se eliminó correctamente'
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def is_user?
    @post = Post.find(params[:id])
    unless current_user.id == @post.user_id
      flash[:alert] = 'Ojo! No tienes permisos para hacer eso'
      redirect_to posts_path
    end
  end

  def post_params
    params.require(:post).permit(:title, :content, :category_id, :user_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then 'alert alert-dismissible alert-info'
    when 'success' then 'alert alert-dismissible alert-success'
    when 'error' then 'alert alert-dismissible alert-danger'
    when 'alert' then 'alert alert-dismissible alert-warning'
    end
  end

  def gravatar_url(email, size)
    gravatar_id = Digest::MD5.hexdigest(email).downcase
    default_url = 'http://mysite.com/myavatar.png' # Acá puedo poner una ruta para una imagen propia.
    default_url = 'retro'
    url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=#{CGI.escape(default_url)}"
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def bg_badge(category)
    case category
    when 'Programación' then 'badge-primary'
    when 'Javascript' then 'badge-secondary'
    when 'Ruby' then 'badge-danger'
    when 'Ruby on rails' then 'badge-warning'
    when 'React' then 'badge-info'
    when 'React native' then 'badge-success'
    when 'NodeJS' then 'badge-success'
        end
end
end

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>">
  <div class="container-fluid my-4">
  <div class="row">
    <div class="col-md-2 mx-auto mt-1">
      <%= image_tag gravatar_url(comment.user.email, 60), alt: "", class:"rounded-circle mx-auto d-block" %>
    </div>
    <div class="col-md-10  bg-hint pl-2">
      <p class="text-muted text-left"><%= comment.user.username %> escribió:</p>
      <p class="text-secondary"><%= comment.content %></p>
      <!-- <p><span class="text-muted float-right"><em></em></span></p> -->
      <% if user_signed_in? %>
      <% if current_user.id == comment.user.id %>
      <%= link_to (fa_icon "eraser"), [comment.post, comment], remote: true, method: "delete", data:{ confirm: "Estás seguro de eliminar el comentario?"}, class:"float-right m-1", id:"delete-comment" %>
      <%= link_to (fa_icon "pencil"), edit_post_comment_path(@post, comment) , class:"float-right m-1" %>
      <% end %>
      <% end %>

    </div>
  </div>

</div>
</div>

app/views/comments/_form.html.erb
<div class="container-fluid my-4">
  <div class="row">
    <div class="col-md-2 mx-auto mt-1">
     <%= image_tag gravatar_url(current_user.email, 60), alt: "", class:"rounded-circle mx-auto d-block" %>
    </div>
    <div class="col-md-10 p-0">
      <%= form_for [@post, @comment], remote: true do |f| %>
      
      <!--
      collection.build(attributes = {}, …) Returns one or more new objects of the collection type that have been instantiated with attributes and linked to this object
      through a foreign key, but have not yet been saved. Note: This only works if an associated object already exists, not if it‘s nil!
      -->
      
      <%= render "posts/error_comment", :target => @comment %>
      
      <%= f.text_area :content, class:"form-control", id:"comment-box", placeholder: "Escribir comentario..." %>
      <br>
      <%= f.submit "Comentar!", class:"btn btn-success float-right"%>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_form_edit.html.erb
<div class="container-fluid my-4">
  <div class="row">
    <div class="col-md-2 mx-auto mt-1">
    </div>
    <div class="col-md-8 p-0">
      <div class="m-5">
        <%= image_tag gravatar_url(current_user.email, 180), alt: "", class:"rounded-circle mx-auto d-block" %>
        <h3 class="text-center m-2"><strong><%=current_user.username%></strong></h3>
      </div>

      <%= form_for ([@post, @comment]) do |f| %>

      <!--
      collection.build(attributes = {}, …) Returns one or more new objects of the collection type that have been instantiated with attributes and linked to this object
      through a foreign key, but have not yet been saved. Note: This only works if an associated object already exists, not if it‘s nil!
      -->

      <!-- <%= render "posts/error_comment", :target => @comment %> -->

      <%= f.text_area :content, class:"form-control", placeholder: "Escribir comentario..." %>
      <br>
      <%= f.submit "Editar!", class:"btn btn-success float-right"%>
      <% end %>
      <%= link_to  "Mejor después...", post_path(@post), class:"btn btn-outline-danger" %>

    </div>
    <div class="col-md-2 mx-auto mt-1">
    </div>
  </div>
</div>

app/views/comments/create.js.erb
$("<%= escape_javascript(render(@comment)) %>").appendTo('#comment-list');
$('#comment-box').val('');

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').fadeOut(1000);

app/views/comments/edit.html.erb
<%= render 'form_edit' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- <a class="navbar-brand" href="#">SuperBlog</a> -->
  <%= link_to  "SuperBlog", posts_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03"
    aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"> Usuarios <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Categorias</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form> -->
    <div class="my-2 my-lg-0">
      <% if !user_signed_in? %>
      <%= link_to  "Registrarse", new_user_registration_path, class:"btn btn-secondary my-2 my-sm-0"  %>
      <%= link_to  "Login", new_user_session_path, class:"btn btn-secondary my-2 my-sm-0" %>
      <% else %>
      <%= link_to  "Crear post", new_post_path, class:"btn btn-success" %>
      <%= link_to  "Logout", destroy_user_session_path, method: :delete, class:"btn btn-secondary my-2 my-sm-0" %>
      <% end %>
    </div>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render  "layouts/navbar"%>
    
    <% flash.each do |key, value| %>
   <div class="msg-alert">
    <div class="<%= flash_class(key) %>">
      <p class="mb-0"><%= value %></p> 
    </div>
    <% end %>
   </div>
    
     <%= yield %>

  <script>
    $(".alert").fadeIn(500).css("opacity", "0.85").delay(6000).slideUp(1000);
    $(".msg-alert").on('click', '.alert', function () { $(this).remove() })
  </script>
  </body>
</html>

app/views/posts/_error_comment.html.erb
<div>
  <% if @comment.errors.any? %>
  <ul class="alert alert-danger">
    <h2>Error!</h2>
    <% @comment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
</div>

app/views/posts/_form.html.erb
<div class="container-fluid my-5">
  <div class="row">

    <div class="col-md">
      1 od 3
    </div>

    <div class="col-md-8">
      <div class="mx-2">
      <%= form_for @post do |f| %>
        
      <div>
        <% if @post.errors.any? %>
        <ul class="alert alert-danger">
          <h2>Error!</h2>
          <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
        <% end %>
      </div>
      
      <div class="form-group">
          <%= f.label :title, "Titulo", class:"form-check-label" %>
          <%= f.text_field :title, class:"form-control", placeholder:"Escribe tu titulo aquí" %>
        </div>

        <div class="form-group">
          <%= f.label :content, "Post", class:"form-check-label" %>
          <%= f.text_area :content, class:"form-control", placeholder:"Escribe el cuerpo de tu post aquí", rows:"10"  %>
        </div>

        <div class="form-group">
          <%= f.label :category, "Categoria" %>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: "Escoja una categoría para tu post"}, {class: "custom-select"})%>
        </div>

        <%= f.submit "Publicar!", class:"btn btn-outline-warning btn-lg float-right" %>
        <% end %>
       <%= link_to  "Mejor después...", posts_path, class:"btn btn-outline-danger" %>

      </div>
    </div>
    <div class="col-md">
      3 of 3
    </div>
  </div>

app/views/posts/edit.html.erb
<h1  class="text-center my-4">Editar Post</h1>

<%= render   "form" %>

app/views/posts/index.html.erb
<div class="container-fluid my-5">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 px-5">
      <div>
        <h1 class="text-center bg-warning">Posts + recientes</h1>

        <div class="my-5">
          <% @posts.each do |post| %>
          <div class="my-4">
            <!-- <%= link_to  post_path(post) do %> -->
              <h3><strong><%= post.title %></strong></h3>
            <!-- <% end %> -->
            <p class="pl-2 mt-2 mb-3"><%= truncate(post.content, length: 250) %></p>
            
            <p class="d-inline"><%= time_ago_in_words(post.created_at) %> atrás, Por <%= post.user.username %></p>
            
            <div class="my-2 float-right">
              <% if user_signed_in? %>
                <% if current_user.id == post.user.id %>
                <%= link_to  (fa_icon "eraser 2x"), post_path(post), method: :delete, data: {confirm: "Está seguro de eliminar este artículo?"}  %>
                <%= link_to  (fa_icon "pencil 2x"), edit_post_path(post)  %>
                <% end %>
              <% end %>
              <%= link_to (fa_icon "eye 2x"), post_path(post)%>
            </div>            
            <% end %>
            
          </div>
        </div>
        
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/posts/new.html.erb
<h1 class="text-center my-4">Crear un nuevo Post</h1>

<%= render  "form" %>

app/views/posts/show.html.erb
<div class="container-fluid my-5">
  <div class="row">

    <div class="col-md">
      <div class="card text-white bg-warning mb-3 mx-auto" style="max-width: 20rem;">
        <div class="card-header text-center"> <%= @post.user.username %> </div>
        <div class="card-body">
          <%= image_tag gravatar_url(@post.user.email , 150), alt: "", class:"rounded-circle mx-auto d-block" %>
          <h4 class="card-title mt-2 text-center">Acerca del autor</h4>
          <p class="card-text text-center">Some quick example text to build on the card title and make up the bulk of
            the card's content.
            Some quick example text to build on the card title and make up the bulk of the card's content.
          </p>
        </div>
      </div>

      <div class="text-center my-5">
        <%= link_to  (fa_icon "arrow-circle-left 5x"), posts_path, class:"rm-deco"%>
      </div>

    </div>

    <div class="col-md-6">
      <div class="mx-2">
        <h1 class="font-weight-bold""><%= @post.title %></h1>
        <p class=" mt-3"><%= @post.content %></p>
          <span
            class="badge badge-pill <%= bg_badge(@post.category.name) %> mt-2 float-right"><%= @post.category.name %></span>
          <div class="my-4">
            <% if user_signed_in? %>
            <% if current_user.id == @post.user.id %>
            <%= link_to  "Editar", edit_post_path(@post), class:"btn btn-outline-primary" %>
            <%= link_to  "Eliminar?", post_path(@post), method: :delete, data: {confirm: "Está seguro de eliminar este artículo?"}, class:"btn btn-outline-danger"  %>
            <% end %>
            <% end %>
            <div class="my-5">
              <h2> <mark class="bg-warning">Comentarios</mark> </h2>
              <div class="my-4">

                <div id="comment-list">
                  <%= render @post.comments.reject(&:new_record?) %>
                </div>

                <div id="comment-form">
                  <% if user_signed_in? %>
                  <%= render 'comments/form' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>

    <div class="col-md">
      <div>
        <div class="my-3">
          <h3>Más posts por <strong><%= @post.user.username %></strong> </h3>
        </div>
        <ul class="list-group">
          <% @post.user.posts.each do |post| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <p><%= link_to  post.title, post_path(post), class:"rm-deco font-neu"%></p>
            <span class="badge badge-primary badge-pill"> <%= post.comments.count %> </span>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>